INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 1', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 2', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 3', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 4', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 5', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 6', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 7', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 8', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 9', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 10', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 11', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 12', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 13', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 14', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 15', true);
INSERT INTO menu_category(menu_category_name, is_active) VALUES ('Menu Category 16', true);

INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 1', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 2', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 3', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 4', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 5', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 6', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 7', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 8', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 9', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 10', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 11', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 12', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 13', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 14', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 15', true);
INSERT INTO supply_category(supply_category_name, is_active) VALUES ('Supply Category 16', true);

INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 1', 'UOM 1', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 2', 'UOM 2', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 3', 'UOM 3', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 4', 'UOM 4', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 5', 'UOM 5', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 6', 'UOM 6', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 7', 'UOM 7', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 8', 'UOM 8', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 9', 'UOM 9', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 10', 'UOM 10', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 11', 'UOM 11', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 12', 'UOM 12', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 13', 'UOM 13', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 14', 'UOM 14', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 15', 'UOM 15', true);
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation, is_active) VALUES ('Unit of Measurement 16', 'UOM 16', true);


INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 1', 'Address 1', '09273173101', 'Person 1', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 2', 'Address 2', '09273173102', 'Person 2', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 3', 'Address 3', '09273173103', 'Person 3', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 4', 'Address 4', '09273173104', 'Person 4', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 5', 'Address 5', '09273173105', 'Person 5', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 6', 'Address 6', '09273173106', 'Person 6', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 7', 'Address 7', '09273173107', 'Person 7', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 8', 'Address 8', '09273173108', 'Person 8', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 9', 'Address 9', '09273173109', 'Person 9', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 10', 'Address 10', '09273173110', 'Person 10', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 11', 'Address 11', '09273173111', 'Person 11', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 12', 'Address 12', '09273173112', 'Person 12', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 13', 'Address 13', '09273173113', 'Person 13', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 14', 'Address 14', '09273173114', 'Person 14', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 15', 'Address 15', '09273173115', 'Person 15', true);
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person, is_active) VALUES ('Supplier 16', 'Address 16', '09273173116', 'Person 16', true);

INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 1', 0, 1, 1, 1, 11, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 2', 0, 2, 2, 2, 12, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 3', 0, 3, 3, 3, 13, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 4', 0, 4, 4, 4, 14, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 5', 0, 5, 5, 5, 15, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 6', 0, 6, 6, 6, 16, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 7', 0, 7, 7, 7, 17, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 8', 0, 8, 8, 8, 18, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 9', 0, 9, 9, 9, 19, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 10', 0, 10, 10, 10, 20, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 11', 0, 11, 11, 11, 21, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 12', 0, 12, 12, 12, 22, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 13', 0, 13, 13, 13, 23, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 14', 0, 14, 14, 14, 24, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 15', 0, 15, 15, 15, 25, true);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, is_active) VALUES ('Supply 16', 0, 16, 16, 16, 26, true);

INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 1', 10, 1, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 2', 11, 2, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 3', 12, 3, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 4', 13, 4, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 5', 14, 5, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 6', 15, 6, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 7', 16, 7, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 8', 17, 8, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 9', 18, 9, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 10', 19, 10, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 11', 20, 11, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 12', 21, 12, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 13', 22, 13, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 14', 23, 14, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 15', 24, 15, 20, true);
INSERT INTO menu(menu_name, menu_price, menu_category_id, number_of_servings_left, is_active) VALUES ('Menu 16', 25, 16, 20, true);

INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (1, 1, 3);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (1, 2, 4);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (1, 3, 5);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (2, 4, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (3, 5, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (4, 6, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (5, 7, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (6, 8, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (7, 9, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (8, 10, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (9, 11, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (10, 12, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (11, 13, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (12, 14, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (13, 15, 1);
INSERT INTO menu_ingredients(menu_id, supply_id, quantity) VALUES (14, 16, 1);