INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 1');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 2');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 3');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 4');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 5');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 6');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 7');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 8');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 9');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 10');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 11');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 12');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 13');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 14');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 15');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 16');

INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 1');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 2');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 3');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 4');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 5');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 6');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 7');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 8');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 9');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 10');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 11');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 12');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 13');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 14');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 15');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 16');

INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 1', 'UOM 1');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 2', 'UOM 2');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 3', 'UOM 3');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 4', 'UOM 4');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 5', 'UOM 5');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 6', 'UOM 6');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 7', 'UOM 7');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 8', 'UOM 8');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 9', 'UOM 9');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 10', 'UOM 10');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 11', 'UOM 11');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 12', 'UOM 12');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 13', 'UOM 13');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 14', 'UOM 14');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 15', 'UOM 15');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 16', 'UOM 16');


INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 1', 'Address 1', '09273173101', 'Person 1');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 2', 'Address 2', '09273173102', 'Person 2');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 3', 'Address 3', '09273173103', 'Person 3');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 4', 'Address 4', '09273173104', 'Person 4');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 5', 'Address 5', '09273173105', 'Person 5');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 6', 'Address 6', '09273173106', 'Person 6');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 7', 'Address 7', '09273173107', 'Person 7');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 8', 'Address 8', '09273173108', 'Person 8');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 9', 'Address 9', '09273173109', 'Person 9');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 10', 'Address 10', '09273173110', 'Person 10');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 11', 'Address 11', '09273173111', 'Person 11');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 12', 'Address 12', '09273173112', 'Person 12');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 13', 'Address 13', '09273173113', 'Person 13');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 14', 'Address 14', '09273173114', 'Person 14');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 15', 'Address 15', '09273173115', 'Person 15');
INSERT INTO supplier(supplier_name, supplier_address, supplier_contact_number, supplier_contact_person) VALUES ('Supplier 16', 'Address 16', '09273173116', 'Person 16');

INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 1', 0, 1, 1, 1, 11, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 2', 0, 2, 2, 2, 12, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 3', 0, 3, 3, 3, 13, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 4', 0, 4, 4, 4, 14, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 5', 0, 5, 5, 5, 15, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 6', 0, 6, 6, 6, 16, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 7', 0, 7, 7, 7, 17, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 8', 0, 8, 8, 8, 18, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 9', 0, 9, 9, 9, 19, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 10', 0, 10, 10, 10, 20, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 11', 0, 11, 11, 11, 21, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 12', 0, 12, 12, 12, 22, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 13', 0, 13, 13, 13, 23, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 14', 0, 14, 14, 14, 24, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 15', 0, 15, 15, 15, 25, false);
INSERT INTO supply(supply_name, supply_quantity, supplier_id, unit_of_measurement_id, supply_category_id, minimum_quantity, in_minimum_quantity) VALUES ('Supply 16', 0, 16, 16, 16, 26, false);